#!/usr/bin/env python3
"""
Derive the Code Brain interactive-explainer base from the keyed dial.

`code-brain.webp` is the keyed, TRANSPARENT graphite dial (generated by
scripts/gen-explainer-codebrain.sh, then scripts/key-explainer-art.py
--no-trim --resize 1672x941 --paper-pct 85). It is the complete diagram and the
no-JS / reduced-motion fallback.

This script makes the INTERACTIVE base `code-brain-dial.webp` by ERASING the
lower-right "dawn cluster" (the rising sun, the 08:30 marker, the newspaper
strip) to fully transparent — so CodeBrainExplainer.astro can "print" the dawn
back as LIVE SVG/CSS (amber wash + rising sun + 08:30 + masthead) when the reader
drags dusk → dawn. Because the art is already transparent, we clear alpha to 0 in
the box (NOT paint a fill, which would reintroduce a visible card).

This (not a separate generator) is the committed reproducibility artifact for the
base. See docs/specs/interactive-explainer-rollout-v1.md §2.

Usage: python3 scripts/prep-explainer-codebrain.py
Requires: pip install Pillow
"""
from PIL import Image

SRC = "public/assets/projects/explainers/code-brain.webp"
OUT = "public/assets/projects/explainers/code-brain-dial.webp"

# Dawn-cluster erase box in source pixels (1672x941). Re-derived from the keyed
# art: cluster content is x[1080,1487] y[735,873]; the dial ring's right edge at
# the box top (y≈725) is x≈1050, so the ~16px gap keeps the ring + SYNTHESIZE
# node/label untouched.
BOX = (1066, 725, 1503, 887)  # (x0, y0, x1, y1)

im = Image.open(SRC).convert("RGBA")
px = im.load()
x0, y0, x1, y1 = BOX
for y in range(y0, y1):
    for x in range(x0, x1):
        r, g, b, _ = px[x, y]
        px[x, y] = (r, g, b, 0)  # clear to transparent
im.save(OUT, "WEBP", lossless=True, method=6)
print(f"erased dawn cluster {SRC} -> {OUT}  size={im.size}  box={BOX}")
